/* REVISAO
FUNÇÃO
TIPO
	RETORNAM VALOR: SAO FUNÇÕES QUE RETORNAM UM ÚNICO VALOR PARA QUEM 
	CHAMOU (VALOR: INTEIRO, REAL OU CARACTER);
	DEVEM TER PELO MENOS UMA VARIÁVEL DO TIPO DA FUNÇÃO PARA SER USADO NO RETURN.

	NÃO RETORNAM VALOR: TAMBÉM CHAMADOS DE ROTINAS OU PROCEDIMENTOS. SÃO FUNÇÕES QUE 
	EXECUTAM UM DETERMINADO CONJUNTO DE COMANDOS EM C, FUNÇÕES QUE RETORNMA UMA ESTRUTURA COMPOSTA
	( VETOR, MATRIZ, STRING, STRUCT). TAMBEM SÃO FUNÇOES QUE NAO RETORNAM VALOR.
	O TIPO DAS FUNÇÕES QUE NÃO RETORNAM VALOR É O VOID.

PASSAGEM DE PARAMETROS: SÃO VALORES QUE PASSAMOS AS FUNÇOES PARA REALIZAREM O SEU PROCESSAMENTO, 
PODENDO SER:
	POR VALOR: NESTE CASO O VALOR PASSADO É COPIADO EM OUTRA POSIÇAO DE MEMORIA(COMO 
	SE FOSSE OUTRA VARIAVEL). TODAS AS VARIAVEIS SIMPLES (INTEIROS, REAIS E CARACTERES)
	SÃO, POR PADRÃO, PASSADOS POR VALOR.(É OUTRO OBJETO)

	POR REFERENCIA: NESTE CASO É PASSADO O ENDEREÇO REAL DA VARIAVEL ( SIMPLES E/OU COMPOSTA),
	ASSIM, QUALQUER MODIFICAÇÕES DO VALOR DA VARIÁVEL DENTRO DA FUNÇÃO, PERMANECE FORA TAMBÉM.
	(É A REFERENCIA DA VARIAVEL, ALTERA TODOS OS LUGARES);


TODAS AS VARIAVEIS COMPOSTAS (VETORES, MATRIZES, STRING, STRUCTS) SÃO PASSADAS POR REFERENCIA.
