/*UM AFUNÇAO EM C PODE OU NAO RETORNAR VALOR,.
CASO RETORNE UM VALOR INTEIRO,M REAL OU CARACTER, O TIPO DA FUNÇAO CORRESPONDE AO VALOR RETORNADO.
CASO NAO RETORNE VALOR, OU RETORNE UM VETOR, MATRIZ OU STRING O TIPO SERÁ VOID,
PASSAGEM DE PARAMETROS: OS PARAMETROS SÃO VALORES E OU VARIAVEIS QUE PASSAMOS A FUNÇAO PARA QUE POSSA REALIZAR USUA AÇAO.

OS VALORES PASSADOS PODEM SER POR:]
	VALOR: NESTE CASO É FEITA UMA COPIA DO VALOR
	PASSADO EM OUTRA POSIÇAO DE MEMORIA OU;
	
	REFERENCIA: NESSE CASO É PASSADO O ENDEREÇO REAL DA
	VARIAVEL. TIPOS COMPOSTOS SEMPRE SÃO PASSADO POR REFEREÊNCIA.
	
	COMPLETE:
		
		int conta_num(int vet[10]){
		int i, qtd=0;
		for(i=0;i<10;i++)
			if(vet[i]%3==0;
				qtd++;
		return qtd;
	}
	
	void naosei(int v1[10], int v2[10]){
	int i;
	for(i=0;i<10;i++)
		v2[i]=v1[9-i];
	return;
}

OQUE FAZ A FUNÇAO ACIMA;

INVERTTE A ORDEM DO VETOR 1 PARA O CONTRARIO NO VETOR 2
EX: V1 123456789 V2 987654321
*/
//2)ESCREVA FUNÇOES PARA:
//a)RECEBER O VALOR DO RAIO DE UMA CIRCUNFERENCIA E RETORNE O TAMANHO DA CIRCUNFERENCIA.
//b)RECEBA AS DIMENSOES DE UM RETANGULO E RETORNE O VALOR DO PERIMETRO .
//c)RECEBA UM NUMERO INTEIRO E RETORNE A QUANTIDADE DE DIVISORES DO Nº
//d)RECEBA 2 NUMEROS INTEIROS E RETORNE O VALOR DE MMC;
//e)RECEBA UM VETOR DE 10 POSIÇOES DE INTEIROS E UM Nº INTEIRO. RETORNE QUANTOS ELEMENTOS DO VETOR SAO IGUAIS AO Nº
//f)RECEBA UM VETOR DE 10 POSIÇOES DE INTEIROS E UM Nº INTEIRO. RETORNE TODOS OS ELEMENTOS DO  MULTIPLICADOS PELO Nº
//g)RECEBA UMA MATRIZ 3X3 E RETORNE A SOMA DA 2@LINHA
//h)RECEBA UMA MATRIZ 3X3 E RETORNE QUANTOS ELEMENTOS DA MATRIZ SAO PARES.VETOR
//i)RECEBA UMA MATRIZ 3X3 E RETORNE QUANTOS ELEMENTOS DA MATRIZ SAO NEGATIVOS
//j)RECEBA 2 MATRIZES 3X3 E RETORNE A SOMA DAS MATRIZES

