/* 
1 o que são registros?

2 NA LINGUAGEM C PODEMOS DEFINIR REGISTROS? CASO POSITIVO COMO FAZEMOS?

3 PODEMOS USAR PARA ARMAZENAMENTO DE DADOS OS REGISTROS DECLARADOS? justifique

4 DECLARE OS SEGUINTES CAMPOS PARA RAÇAS DE CÃES;
		raça: string de 30
		porte: 1-pequeno, 2-MEDIO, 3-grande
		pelagem: 1_curto; 2_longo;
		origem: string de 30

		
		CONSIDERAR PARA AS PROXIMAS QUESTOES UM VEOTR DE 10 REGISTROS DA CDECLARA~ÇAO DA QUESTAO ANTERIOR
	5 ESCREVER UM AFUNÇAO QUE LEIA OS DADOS DE UMA RAÇA
	
	
	6 ESCREVER UMA FUNÇAO QUE EXIBA OS DADOS DE UMA RAÇA;
	
	7 ESCREVE RUM GFUNAÇOAO QUE EXIBA OS DADOS DETODAS AS RAÇAS DIGITADAS.
	
	
	8 ESCREVER UMA FUNÇAO QUE EXIBA AS SEGUINTES OPÇOES:
	
		A) CADASTRAR UMA RAÇA
		B) EXIBIR DADOS DEUMA RAÇA
		C) LISTAR TODAS AS RAÇAS
		D) SAIR
		
	9 ESCREVER UM ´PROGRAMA PRINCIPAL QUE MANIPULE AS FUNÇOES SOLICITADAS ANTERIORMENTE.
	
	OBS: SE ENTREGAR IMPRESSO NA PROXIMA O LAUNO A GANHA UM PONTO NA P2;
